version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      # - run:
      #     name: Wait for DB
      #     command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: RAILS_ENV=test bundle exec rails db:schema:load --trace
      - run:
          name: Run tests
          command: bundle exec rails test
      # - ruby/rubocop-check
